# Generated by Django 5.2.12 on 2026-04-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCases',
            fields=[
                ('case_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('spo2', models.IntegerField()),
                ('systolic_bp', models.IntegerField()),
                ('severity_score', models.IntegerField()),
                ('urgency_level', models.CharField(max_length=50)),
                ('required_specialist', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'emergency_cases',
            },
        ),
        migrations.CreateModel(
            name='Ambulances',
            fields=[
                ('ambulance_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('last_updated_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'ambulances',
            },
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('hospital_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hospital_type', models.CharField(max_length=50)),
                ('has_icu', models.IntegerField()),
                ('max_icu_beds', models.IntegerField()),
            ],
            options={
                'db_table': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.emergencycases')),
                ('severity_score', models.IntegerField()),
                ('urgency_level', models.CharField(max_length=50)),
                ('needs_icu', models.IntegerField()),
                ('required_specialist', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'triage',
            },
        ),
        migrations.CreateModel(
            name='EventLogs',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emergencycases')),
            ],
            options={
                'db_table': 'event_logs',
            },
        ),
        migrations.CreateModel(
            name='HospitalDynamicStatus',
            fields=[
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.hospitals')),
                ('available_icu_beds', models.IntegerField()),
                ('current_load_percentage', models.FloatField()),
                ('avg_intake_delay', models.IntegerField()),
                ('readiness_score', models.FloatField()),
                ('last_updated_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'hospital_dynamic_status',
            },
        ),
        migrations.AddField(
            model_name='emergencycases',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patients'),
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta', models.IntegerField()),
                ('score', models.FloatField()),
                ('compatibility', models.CharField(max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emergencycases')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospitals')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='AmbulanceAssignment',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.emergencycases')),
                ('eta_to_patient', models.IntegerField()),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ambulances')),
            ],
            options={
                'db_table': 'ambulance_assignment',
            },
        ),
    ]
