# Generated by Django 5.2.12 on 2026-04-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlogs',
            name='event_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventlogs',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
