# Generated by Django 5.2.12 on 2026-04-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_eventlogs_event_id_alter_eventlogs_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycases',
            name='scene_context',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
